### ISSUE TITLE
Not getting expected frequencies    

### ISSUE THREAD

**Issue by darkoverlordofdata** [peter-suggate/wasm-audio-app#4]
First it shows 57hz, which I assume is line hum, then it switches to 1380, and I have no idea where it’s getting that – I'm hitting the E string, so I’m expecting about 440hz. 

I know that my rig works plugged into my computer, I’ve been playing with WebAudio lately myself - https://github.com/darkoverlordofdata/amp-sim / https://darkoverlordofdata.com/amp-sim/  - and it picks up what I’m playing in the other browser window, and plays it back over my headphones. But I’m just using js, I’m really interested is using rust for this.

**Comment by darkoverlordofdata** [comment]
Sorry for the confusion – the face guard on my fender guitar tuner apparently says 440 hz no matter what string I am on.  
I was able to remove the line hum by holding the guitar rather than leaving it in the holder – I blame the cheap sound cards in laptops for that. 

What I am left with though, and this was a cause for my confusion, is that the low E string doesn’t register at all. The 5 higher strings all work correctly, but when I hit the low E string, it shows nothing – or else just the line hum if I set it down. 

So, looks like it works for the most part.

**Comment by peter-suggate** [comment]
Thanks for the update @darkoverlordofdata. 

I'm not surprised that the software is struggling to pick up the E string. It's probably because of the presence of considerable overtones on that low string. One thing you could try is lowering the clarity threshold:

```
    // The clarity measure describes how coherent the sound of a note is. For
    // example, the background sound in a crowded room would typically be would
    // have low clarity and a ringing tuning fork would have high clarity.
    // This threshold is used to accept detect notes that are clear enough
    // (valid values are in the range 0-1).
    const CLARITY_THRESHOLD: f32 = 0.6;
```

Try a value of 0.4 or 0.5 and see if that helps?

This is at:
https://github.com/peter-suggate/wasm-audio-app/blob/master/wasm-audio/src/lib.rs
Line 45
