### ISSUE TITLE
Not working on Chrome 91

### ISSUE THREAD

**Issue by rowild** [peter-suggate/wasm-audio-app#5]
I get almost the same error that Firefox throws:

```
Unhandled Rejection (Error): Failed to load audio analyzer WASM module. Further info: Failed to load audio analyzer worklet at url: PitchProcessor.js. Further info: The user aborted a request.
````

Any idea what changed since you wrote that fantastic tutorial?
https://www.toptal.com/webassembly/webassembly-rust-tutorial-web-audio

**Comment by peter-suggate** [comment]
@rowild , it's still working for me in Chrome 91.

This message will also show when either no working audio device is available or the user has not specifically allowed the browser to access audio. Do you recall seeing a popup near the address bar asking you to allow audio for this webpage? If not, perhaps perform a hard refresh (Shift+Ctrl+R) of the page or check out: https://support.google.com/chrome/answer/2693767?co=GENIE.Platform%3DDesktop&hl=en

Another potential source of the error is that I haven't yet tested how Chome's relatively new tab muting feature affects this. Let me know how you get on..

**Comment by rowild** [comment]
@peter-suggate Thanks for your fast response! – The navigator permissions are set properly, the tab also shows the red "recording" dot.

But if I understand you properly, this app needs a decent sound device like an external sound card? I only have a USB webcam (Logitech) and USB headphones with a mic. (However, using those with "regular" (JS) web audio recording solutions usually work...)

Same thing happens in Brave and Edge (which are both Chromium-based).

Usually those things (= navigator permission items like audio streaming access) need https, with "localhost" being an exception. Could that be it, when it comes to wasm?

![Bildschirmfoto 2021-06-26 um 21 01 54](https://user-images.githubusercontent.com/213803/123524570-90bde000-d6cb-11eb-9937-0445fd823020.png)

**Comment by peter-suggate** [comment]
Strange. The warning about SharedArrayBuffer in the console is something I haven't seen before but it's unlikely to be causing this given it's only a deprecation so far. Have you tried having only one of your devices attached at a time? You will not need external hardware. My laptop's built-in studio was sufficient for example.

**Comment by rowild** [comment]
Oh my god, I am so ashamed!!! When learning along with your tutorial, I typed everything, no copy-&-paste. Then, when it didn't work, I used your repo – but totally forgot to do those things like `wasm-pack build ...` and copying over the resulting folder etcetc. 

Of course, after doing all that, you app is working perfectly fine! So sorry for taking away your time!

**Comment by peter-suggate** [comment]
Glad to hear you resolved it, thanks for persisting with it. I realize that error message is exceedingly unhelpful. I wonder if I can detect your scenario and display a better message. Food for thought.
